project_id = "owgaselrqehbhuseaebr"

[functions.upload-image]
verify_jwt = false

[functions.cleanup-old-orders]
verify_jwt = false

[functions.notify-new-order]
verify_jwt = false

[functions.notify-admin-new-user]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false